# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password:
  strict: false
  pool: 5
  socket: <%= ENV['DAPHY_MYSQL_SOCKET'] || '/tmp/mysql.sock' %>
  host: localhost


development:
  <<: *default
  database: famiphotos_development

test:
  <<: *default
  database: famiphotos_test

famiphotos_master_development:
  <<: *default
  database: famiphotos_development

famiphotos_slave_development:
  <<: *default
  database: famiphotos_development

famiphotos_master_test:
  <<: *default
  database: famiphotos_test

famiphotos_slave_test:
  <<: *default
  database: famiphotos_test

# production:
#  <<: *default
#  database: db/production.sqlite3
